### ISSUE TITLE
IT classes

### ISSUE THREAD

**Issue by iewi** [DevaDixon/Pathway_Guide#8]
This isn't a bug per se, but I noticed that the class list for IT is off, in more ways than one.

First, shouldn't the class be kinda like MATH 251: Calculus I, or something like that?

Second, these aren't the classes for IT. How are you getting the course list for a subpathway, @thepunctuatedhorizon ? I think I put the class list in the database. Use getSubPathwayClasses, if you aren't already.

![class_list_off](https://cloud.githubusercontent.com/assets/13700053/16654822/83e66c0a-4425-11e6-89f1-cb4a8f3330f9.png)

**Comment by thepunctuatedhorizon** [comment]
That is a remnant of the old data structure, it's still there because I haven't fully changed over to the database.

As in, it works.  We may have to keep it in using the old data structure (modifying the fields of course) until we figure out how to make the CourseClassLoader play nicely with the database.  

I think the trouble I'm having adapting to the database may signal we put it on the todo list while we perfect all the visual elements.

**Comment by thepunctuatedhorizon** [comment]
The most recent version fixes this issue
